/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aws.sqs;

import org.junit.Test;
import static org.junit.Assert.*;

public class SQSClientTest {
    @Test public void testAppHasAGreeting() {
        SQSClient classUnderTest = new SQSClient();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
